package com.mediaxa.business.suite.data.printing

import com.mediaxa.business.suite.data.local.entity.Transaction
import com.mediaxa.business.suite.data.local.entity.TransactionItem
import com.mediaxa.business.suite.data.local.entity.StoreSetting
import kotlinx.coroutines.delay

sealed class PrintResult {
    object Success : PrintResult()
    data class Failure(val errorMessage: String) : PrintResult()
}

class PrinterService {

    /**
     * Simulates printing via Bluetooth.
     * In Phase 10, this will connect to Bluetooth sockets using android.bluetooth APIs
     * and transmit the bytes generated by EscPosFormatter.formatEscPosBytes.
     */
    suspend fun printReceipt(
        transaction: Transaction,
        items: List<TransactionItem>,
        settings: StoreSetting
    ): PrintResult {
        // Simulate a minor Bluetooth delay of 1.2 seconds to represent realistic behavior
        delay(1200L)

        // Generate the print payload to verify formatter works without errors
        return try {
            val escPosBytes = EscPosFormatter.formatEscPosBytes(transaction, items, settings)
            if (escPosBytes.isEmpty()) {
                PrintResult.Failure("Format error: Empty byte commands.")
            } else {
                PrintResult.Success
            }
        } catch (e: Exception) {
            PrintResult.Failure("Formatting error: ${e.message}")
        }
    }
}
